Web.MonicaMartinez.Old/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Web.MonicaMartinez.Service;
using Web.MonicaMartinez.Models.ViewModels;
using System.Linq;
using System;
using System.Globalization;

namespace Web.MonicaMartinez.Controllers
{
    public class HomeController : Controller
    {
        private readonly OrderService _orderService;
        private readonly PatientService _patientService;
        //private readonly CultureInfo _cultureInfo;

        public HomeController()
        {
            _orderService = new OrderService();
            _patientService = new PatientService();
            //_cultureInfo = new CultureInfo("en-US", true);
        }

        public ActionResult Index()
        {
            if (User?.Identity == null || !User.Identity.IsAuthenticated)
                return View(new DashboardViewModelList()
                {
                    PedidosRecibidos = new List<OrderViewModel>(),
                    PedidosPreparar = new List<OrderViewModel>(),
                    PedidosEntregados = new List<OrderViewModel>(),
                    PedidosHistoricos = new List<OrderViewModel>(),
                });

            var ordersDto = _orderService.GetOrders().Result;
            var patientsDto = _patientService.GetPatients().Result;

            DashboardViewModelList model;

            if (!ordersDto.Pedidos.Any())
            {
                model = (new DashboardViewModelList()
                {
                    PedidosRecibidos = new List<OrderViewModel>(),
                    PedidosPreparar = new List<OrderViewModel>(),
                    PedidosEntregados = new List<OrderViewModel>(),
                    PedidosHistoricos = new List<OrderViewModel>(),
                });
            }
            else
            {
                model = new DashboardViewModelList()
                {
                    PedidosRecibidos = ordersDto.Pedidos
                       .Where(x => !x.Entregado && x.Recibido && !x.Preparar &&
                           DateTime.Parse(x.Fecha).ToUniversalTime() >= DateTime.Today.AddDays(-7).ToUniversalTime())
                       .Select(x => new OrderViewModel()
                       {
                           Detalle = x.Detalle,
                           Entregado = x.Entregado,
                           Fecha = DateTime.Parse(x.Fecha).ToString("dd/MM/yy"),
                           Id = x.Id,
                           OrdenNumero = x.OrdenNumero,
                           Preparar = x.Preparar,
                           Recibido = x.Recibido,
                           Sucursal = x.Sucursal,
                           IdPaciente = x.IdPaciente,
                           NombreTelefonoPaciente =
                               $"{patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Nombre} {patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Apellido} ({patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Telefono})",
                           ObraSocialPaciente = patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.ObraSocial
                       }).ToList(),
                    PedidosPreparar = ordersDto.Pedidos
                       .Where(x => !x.Entregado && !x.Recibido && x.Preparar &&
                           DateTime.Parse(x.Fecha).ToUniversalTime() >= DateTime.Today.AddDays(-7).ToUniversalTime())
                       .Select(x => new OrderViewModel()
                       {
                           Detalle = x.Detalle,
                           Entregado = x.Entregado,
                           Fecha = DateTime.Parse(x.Fecha).ToString("dd/MM/yy"),
                           Id = x.Id,
                           OrdenNumero = x.OrdenNumero,
                           Preparar = x.Preparar,
                           Recibido = x.Recibido,
                           Sucursal = x.Sucursal,
                           IdPaciente = x.IdPaciente,
                           NombreTelefonoPaciente =
                               $"{patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Nombre} {patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Apellido} ({patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Telefono})",
                           ObraSocialPaciente = patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.ObraSocial
                       }).ToList(),
                    PedidosEntregados = ordersDto.Pedidos
                       .Where(x => x.Entregado &&
                           DateTime.Parse(x.Fecha).ToUniversalTime() >= DateTime.Today.AddDays(-7).ToUniversalTime())
                       .Select(x => new OrderViewModel()
                       {
                           Detalle = x.Detalle,
                           Entregado = x.Entregado,
                           Fecha = DateTime.Parse(x.Fecha).ToString("dd/MM/yy"),
                           Id = x.Id,
                           OrdenNumero = x.OrdenNumero,
                           Preparar = x.Preparar,
                           Recibido = x.Recibido,
                           Sucursal = x.Sucursal,
                           IdPaciente = x.IdPaciente,
                           NombreTelefonoPaciente =
                               $"{patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Nombre} {patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Apellido} ({patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Telefono})",
                           ObraSocialPaciente = patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.ObraSocial
                       }).ToList(),
                    PedidosHistoricos = ordersDto.Pedidos
                       .Where(x => DateTime.Parse(x.Fecha).ToUniversalTime() < DateTime.Today.AddDays(-7).ToUniversalTime())
                       .Select(x => new OrderViewModel()
                       {
                           Detalle = x.Detalle,
                           Entregado = x.Entregado,
                           Fecha = DateTime.Parse(x.Fecha).ToString("dd/MM/yy"),
                           Id = x.Id,
                           OrdenNumero = x.OrdenNumero,
                           Preparar = x.Preparar,
                           Recibido = x.Recibido,
                           Sucursal = x.Sucursal,
                           IdPaciente = x.IdPaciente,
                           NombreTelefonoPaciente =
                               $"{patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Nombre} {patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Apellido} ({patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Telefono})",
                           ObraSocialPaciente = patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.ObraSocial
                       }).ToList(),
                };
            }
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Web.MonicaMartinez.Old/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Web.MonicaMartinez.Service;
using Web.MonicaMartinez.Models.ViewModels;
using Web.MonicaMartinez.Models.DTOs;
using Microsoft.AspNet.Identity;

namespace Web.MonicaMartinez.Controllers
{
    public class OrdersController : Controller
    {
        private readonly OrderService _orderService;
        private readonly PatientService _patientService;

        public OrdersController()
        {
            _orderService = new OrderService();
            _patientService = new PatientService();

        }

        // GET: Orders
        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                var ordersDto = _orderService.GetOrders().Result;
                var patientsDto = _patientService.GetPatients().Result;
                OrderViewModelList model = new OrderViewModelList();

                if (!ordersDto.Pedidos.Any())
                {
                    model.Pedidos = new List<OrderViewModel>();
                    model.Pacientes = patientsDto.Pacientes
                       .Select(x => new PatientViewModel()
                       {
                           Apellido = x.Apellido,
                           DNI = x.DNI,
                           Domicilio = x.Domicilio,
                           Email = x.Email,
                           Fecha = x.Fecha,
                           Id = x.Id,
                           MedHab = x.MedHab,
                           Nombre = x.Nombre,
                           ObraSocial = x.ObraSocial,
                           Sucursal = x.Sucursal,
                           Telefono = x.Telefono,
                           TipoNro = x.TipoNro,
                           Web = x.Web,
                           NombreTelefonoPaciente =
                                   $"{x.Nombre} {x.Apellido} ({ x.Telefono})"
                       }).ToList();
                }
                else
                {
                    model = new OrderViewModelList()
                    {
                        Pedidos = ordersDto.Pedidos
               .Select(x => new OrderViewModel()
               {
                   Detalle = x.Detalle,
                   Entregado = x.Entregado,
                   Fecha = DateTime.Parse(x.Fecha).ToString("dd/MM/yy"),
                   Id = x.Id,
                   OrdenNumero = x.OrdenNumero,
                   Preparar = x.Preparar,
                   Recibido = x.Recibido,
                   Sucursal = x.Sucursal,
                   IdPaciente = x.IdPaciente,
                   NombreTelefonoPaciente =
                       $"{patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Nombre} {patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Apellido} ({patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.Telefono})",
                   ObraSocialPaciente = patientsDto.Pacientes.FirstOrDefault(y => y.Id == x.IdPaciente)?.ObraSocial,
               }).OrderByDescending(x => x.Fecha).ToList(),
                        Pacientes = patientsDto.Pacientes
                       .Select(x => new PatientViewModel()
                       {
                           Apellido = x.Apellido,
                           DNI = x.DNI,
                           Domicilio = x.Domicilio,
                           Email = x.Email,
                           Fecha = x.Fecha,
                           Id = x.Id,
                           MedHab = x.MedHab,
                           Nombre = x.Nombre,
                           ObraSocial = x.ObraSocial,
                           Sucursal = x.Sucursal,
                           Telefono = x.Telefono,
                           TipoNro = x.TipoNro,
                           Web = x.Web,
                           NombreTelefonoPaciente =
                                   $"{x.Nombre} {x.Apellido} ({ x.Telefono})"
                       }).ToList()
                    };
                }
                return View(model);
            }
            catch
            {
                return View("Error");
            }
        }

        // POST: Orders/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(FormCollection collection)
        {
            if (!ModelState.IsValid) return View("Error");
            try
            {
                var model = new OrderDto
                {
                    OrdenNumero = collection["OrdenNumero"],
                    IdPaciente = collection["Paciente"],
                    Sucursal = collection["Sucursal"],
                    Fecha = collection["Fecha"],

                    Recibido = (!string.IsNullOrEmpty(collection["Recibido"]) &&
                        collection["Recibido"] == "recibido") ? true : false,

                    Preparar = (!string.IsNullOrEmpty(collection["Recibido"]) &&
                        collection["Recibido"] == "preparar") ? true : false,

                    Entregado = (!string.IsNullOrEmpty(collection["Entregado"]) &&
                        collection["Entregado"] == "entregado") ? true : false,

                    Detalle = collection["Detalle"],
                    CreadoPor = User.Identity.GetUserName()
                };

                var result = _orderService.CreateOrder(model).Result;
                if (string.IsNullOrEmpty(result)) return View("Error");
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        // POST: Patients/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(FormCollection collection)
        {
            if (!ModelState.IsValid) return View("Error");
            try
            {
                var model = new Dictionary<string, object>
                {
                    { "Id", collection["eId"] },
                    { "OrdenNumero", collection["OrdenNumero"] },
                    { "Telefono", collection["Telefono"] },
                    { "Sucursal", collection["Sucursal"] },
                    {
                        "Recibido",
                        (!string.IsNullOrEmpty(collection["Recibido"]) &&
                            collection["Recibido"] == "recibido") ? true : false
                    },
                    {
                        "Preparar",
                        (!string.IsNullOrEmpty(collection["Recibido"]) &&
                            collection["Recibido"] == "preparar") ? true : false
                    },
                    {
                        "Entregado",
                        (!string.IsNullOrEmpty(collection["Entregado"]) &&
                            collection["Entregado"] == "entregado") ? true : false
                    },
                    { "Detalle", collection["Detalle"] },
                    {"CreadoPor", User.Identity.GetUserName() }

                };

                var result = _orderService.EditOrder(model).Result;
                if (string.IsNullOrEmpty(result)) return View("Error");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Update(FormCollection collection)
        {
            if (!ModelState.IsValid) return View("Error");
            try
            {
                var model = new Dictionary<string, object>
                {
                    { "Id", collection["IdPedido"] },
                    { "Entregado", true },
                    //{ "fecha", DateTime.Today}
                    {"ActualizadoPor", User.Identity.GetUserName() }
                };

                var result = _orderService.EditOrder(model).Result;
                if (string.IsNullOrEmpty(result)) return View("Error");
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }


        // POST: Patients/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(FormCollection collection)
        {
            if (!ModelState.IsValid) return View("Error");
            try
            {
                var result = _orderService.DeleteOrder(collection["dId"]).Result;
                if (string.IsNullOrEmpty(result)) return View("Error");
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

Web.MonicaMartinez.Old/Views/Home/About.cshtml
@{
    ViewBag.Title = "Información";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web.MonicaMartinez.Old/Views/Home/Index.cshtml
@using Web.MonicaMartinez.Models.ViewModels
@model DashboardViewModelList

@if (Request.IsAuthenticated)
{
    <div>
        <div class="logged-index">
            <div class="input-filter">
                <div id="filterInputs" class="inp-pat">
                    @Html.TextBox("Filters", "", new
                    {
                        id = "fNombreTelefonoPaciente",
                        @type = "text",
                        @class = "form-control",
                        @placeholder = "Ej. juan perez 3513413513",
                        @oninput = "handleFiltersDashboards(this, 'NombreTelefonoPaciente');",
                        @autocomplete = "off"
                    })
                </div>
            </div>
            <div class="logged-filter">
                <label id="clean" class="logged-filter-label">
                    <a href="javascript:document.getElementById('#').submit()" class="text-info">Limpiar filtros</a>
                </label>
            </div>
            <div>
                <button type="button" id="primary">
                    Suc. Ruta 20
                </button>
                <button type="button" id="secondary">
                    Suc. Gral. Paz
                </button>
            </div>
        </div>
        <br />
        <br />
        <div>
            <h3 class="text-custom">Pedidos Recibidos</h3>
        </div>

        @using (Html.BeginForm("Update", "Orders", FormMethod.Post,
      new { id = "formUdateOrder", @class = "background-color-custom" }))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("IdPedido");
        }

        <div class="table-responsive d-sm-block text-nowrap">
            <table class="table table-condensed table-striped table-sm">
                <thead>
                    <tr>
                        <th>
                            Obra Social
                        </th>
                        <th>
                            Paciente
                        </th>
                        <th>
                            Detalle / Aclaraciones
                        </th>
                        <th>
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody id="tbody0">
                </tbody>
            </table>
        </div>
        <br />
        <br />

        <div>
            <h3 class="text-custom">Pedidos a Preparar</h3>
        </div>
        <div class="table-responsive d-sm-block text-nowrap">
            <table class="table table-condensed table-striped table-sm">
                <thead>
                    <tr>
                        <th>
                            Obra Social
                        </th>
                        <th>
                            Paciente
                        </th>
                        <th>
                            Detalle / Aclaraciones
                        </th>
                        <th>
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody id="tbody1">
                </tbody>
            </table>
        </div>
        <br />
        <br />

        <div>
            <h3 class="text-custom">Pedidos Entregados</h3>
        </div>
        <div class="table-responsive d-sm-block text-nowrap">
            <table class="table table-condensed table-striped table-sm">
                <thead>
                    <tr>
                        <th>
                            Obra Social
                        </th>
                        <th>
                            Paciente
                        </th>
                        <th>
                            Detalle / Aclaraciones
                        </th>
                        <th>
                            Fecha
                        </th>
                    </tr>
                </thead>
                <tbody id="tbody2">
                </tbody>
            </table>
        </div>

        <br />
        <br />

        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <div class="mb-0 d-flex justify-content-between align-items-center">
                        <div class="btn btn-link btn-block text-left text-muted" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            HISTORICO
                        </div>
                        <div class="icon">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-square" data-toggle="collapse" data-target="#collapseOne" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z" />
                                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z" />
                                <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                            </svg>
                        </div>
                    </div>
                </div>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="table-responsive d-sm-block text-nowrap">
                            <table class="table table-condensed table-striped table-sm">
                                <thead>
                                    <tr>
                                        <th>
                                            Obra Social
                                        </th>
                                        <th>
                                            Paciente
                                        </th>
                                        <th>
                                            Detalle / Aclaraciones
                                        </th>
                                        <th>
                                            Fecha
                                        </th>
                                    </tr>
                                </thead>
                                <tbody id="tbody3">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section scripts {
        <script type="text/javascript">
            const pedidosRecibidos = [...@(Html.Raw(Json.Encode(Model.PedidosRecibidos)))];
            const pedidosPreparar = [...@(Html.Raw(Json.Encode(Model.PedidosPreparar)))];
            const pedidosEntregados = [...@(Html.Raw(Json.Encode(Model.PedidosEntregados)))];
            const pedidosHistoricos = [...@(Html.Raw(Json.Encode(Model.PedidosHistoricos)))];
        </script>
        <script src="~/Scripts/Home/index.js"></script>
    }
}
else
{
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item">
                <div class="back-image-social">
                    <div class="orders-title">
                        <h1>¡RECIBIMOS TODAS LAS <strong>OBRAS SOCIALES</strong>!</h1>
                    </div>

                    <div class="orders-points">
                        <div class="points">
                            <img src="~/Content/img/whatsapp.svg" />
                            <a href="https://wa.me/5493515123726?" target="_blank">Sucursal General Paz</a>
                        </div>
                        <div class="points">
                            <img src="~/Content/img/whatsapp.svg" />
                            <a href="https://wa.me/5493512012115?" target="_blank">Sucursal Ruta 20</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="back-image-orders">
                    <div class="orders-title">
                        <h1>¡PEDÍ TUS MEDICAMENTOS <strong>ONLINE</strong>!</h1>
                    </div>

                    <div class="orders-points">
                        <div class="points">
                            <img src="~/Content/img/whatsapp.svg" />
                            <a href="https://wa.me/5493515123726?" target="_blank">Sucursal General Paz</a>
                        </div>
                        <div class="points">
                            <img src="~/Content/img/whatsapp.svg" />
                            <a href="https://wa.me/5493512012115?" target="_blank">Sucursal Ruta 20</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item active">
                <div class="back-image-local">
                    <div class="orders-title">
                        <h1>¡VISITANOS EN NUESTRAS <strong>FARMACIAS</strong>!</h1>
                    </div>

                    <div class="orders-points">
                        <div class="points">
                            <img src="~/Content/img/whatsapp.svg" />
                            <a href="https://wa.me/5493515123726?" target="_blank">Sucursal General Paz</a>
                        </div>
                        <div class="points">
                            <img src="~/Content/img/whatsapp.svg" />
                            <a href="https://wa.me/5493512012115?" target="_blank">Sucursal Ruta 20</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <br />
    <br />
    <section class="container-fluid container-custom" style=" background-color: #03A688">
        <div class="container" style="max-width: 600px; padding: 75px 0; color: white">
            <h3>Nuestras Farmacias</h3>
            <p style="padding-bottom: 10px">Somos un grupo familiar rodeado de colaboradores que trabajamos día a día para brindarte el mejor servicio y profesionalismo en la actividad farmacéutica. Con más de 30 años de experiencia intentamos  mejorar día a día para atender las nuevas necesidades y demandas de nuestros pacientes.</p>
            <div class="online-orders">
                <div class="business">
                    <i class="fas fa-map-marker-alt fa-2x"></i>
                    <a href=@($"https://www.google.com.ar/maps/place/Av.+Fuerza+Aerea+Argentina+2831,+C%C3%B3rdoba/@-31.4314594,-64.2284042,17z/data=!3m1!4b1!4m5!3m4!1s0x9432a20e22a9b4e3:0x8b12124497443f1b!8m2!3d-31.431464!4d-64.2262155")
                       target="_blank" role="button">
                        Sucursal Ruta 20
                    </a>
                </div>
                <div class="business">
                    <i class="fas fa-map-marker-alt fa-2x"></i>
                    <a href=@($"https://www.google.com/maps/place/Farmacia+M%C3%B3nica+Mart%C3%ADnez+II/@-31.4119617,-64.1624756,16z/data=!4m13!1m7!3m6!1s0x9432a2a6618dfb29:0x8cf9f421af3df90e!2sGral.+Rom%C3%A1n+Deheza+268,+X5004+BCF,+C%C3%B3rdoba!3b1!8m2!3d-31.412001!4d-64.1624321!3m4!1s0x0:0xebac916ffa89c682!8m2!3d-31.4097165!4d-64.1633695")
                       target="_blank" role="button">
                        Sucursal Bº General Paz
                    </a>
                </div>
            </div>


        </div>
    </section>

    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="padding: 20px 0 0 0;">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Content/img/obras.png" class="d-block w-100" alt="slider">
            </div>
            <div class="carousel-item">
                <img src="~/Content/img/obras2.png" class="d-block w-100" alt="slider">
            </div>
            <div class="carousel-item">
                <img src="~/Content/img/obras3.png" class="d-block w-100" alt="slider">
            </div>
            <div class="carousel-item">
                <img src="~/Content/img/obras4.png" class="d-block w-100" alt="slider">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
}